version: '2'

volumes:
  postgisdata:

services:

  postgis:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: 'amigoosm'
      POSTGRES_DB: 'osm'
      POSTGRES_PASSWORD: 'Amigo:)'
    volumes:
      - "postgisdata:/var/lib/postgresql"
    ports:
      - "5432:5432"

  tilestache:
    build: osmbase
    volumes:
      - "./osmdata:/opt/osmdata"
    links:
      - postgis
    ports:
      - "8080:8080"


  app:
    image: php:7.0-apache
    volumes:
      - "./app:/var/www/html/"
    expose:
      - "80"
    ports:
      - "80:80"
